# Generated by Django 4.1.7 on 2023-03-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('design_img', models.ImageField(upload_to='design_img/')),
                ('design_type', models.TextField(default='', max_length=50)),
                ('design_desc', models.TextField(default='', max_length=5000)),
            ],
        ),
    ]
