# Generated by Django 4.1.7 on 2023-03-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0002_designdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdata',
            name='project_name',
            field=models.TextField(default='', max_length=200),
        ),
    ]
