# Generated by Django 4.1.7 on 2023-03-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0003_designdata_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='designdata',
            name='user_type',
            field=models.TextField(default='', max_length=50),
        ),
    ]
