# Generated by Django 4.1.7 on 2023-03-20 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0004_designdata_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TextField(default='', max_length=50)),
                ('end_time', models.TextField(default='', max_length=50)),
                ('appointment_desc', models.TextField(default='', max_length=500)),
                ('architech_id', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(default=0)),
            ],
        ),
    ]
