# Generated by Django 4.1.7 on 2023-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0005_appointmentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdata',
            name='status',
            field=models.TextField(default='', max_length=40),
        ),
    ]
