# Generated by Django 4.1.7 on 2023-03-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0006_appointmentdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdata',
            name='full_name',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointmentdata',
            name='status',
            field=models.TextField(default='In Waiting', max_length=40),
        ),
    ]
