# Generated by Django 4.1.7 on 2023-03-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0007_appointmentdata_full_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentdata',
            old_name='full_name',
            new_name='architech_name',
        ),
        migrations.AddField(
            model_name='appointmentdata',
            name='consumer_name',
            field=models.TextField(default='', max_length=150),
        ),
    ]
