# Generated by Django 4.1.7 on 2023-03-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0008_rename_full_name_appointmentdata_architech_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(default='', max_length=100)),
                ('message', models.TextField(default='', max_length=500)),
            ],
        ),
    ]
