# Generated by Django 4.1.7 on 2023-03-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0012_paymentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('app_id', models.IntegerField(default=0)),
                ('architech_id', models.IntegerField(default=0)),
            ],
        ),
    ]
